"""initial_schema

Revision ID: 13aa8a52fffc
Revises:
Create Date: 2026-07-12 14:13:41.861324
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "13aa8a52fffc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earthquakes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hypocenter", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("depth_km", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("preliminary", "reviewed", "final", "cancelled", name="eventstatus"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("latest_source", sa.String(length=32), nullable=False),
        sa.Column("notified_revision", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_earthquakes_hypocenter"), "earthquakes", ["hypocenter"], unique=False)
    op.create_index(op.f("ix_earthquakes_magnitude"), "earthquakes", ["magnitude"], unique=False)
    op.create_index(
        op.f("ix_earthquakes_origin_time"), "earthquakes", ["origin_time"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(
        op.f("ix_raw_messages_received_at"), "raw_messages", ["received_at"], unique=False
    )
    op.create_index(op.f("ix_raw_messages_source"), "raw_messages", ["source"], unique=False)
    op.create_table(
        "source_health",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("connected", sa.Boolean(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("outage_notified", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "webhook_endpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("encrypted_headers", sa.LargeBinary(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("earthquake_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["earthquake_id"],
            ["earthquakes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("earthquake_id", "revision", name="uq_event_revision"),
    )
    op.create_index(
        op.f("ix_event_revisions_earthquake_id"), "event_revisions", ["earthquake_id"], unique=False
    )
    op.create_table(
        "impact_estimates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("earthquake_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.String(length=36), nullable=False),
        sa.Column("location_name", sa.String(length=100), nullable=False),
        sa.Column("location_latitude", sa.Float(), nullable=False),
        sa.Column("location_longitude", sa.Float(), nullable=False),
        sa.Column("epicentral_distance_km", sa.Float(), nullable=False),
        sa.Column("hypocentral_distance_km", sa.Float(), nullable=False),
        sa.Column("estimated_intensity", sa.Float(), nullable=True),
        sa.Column("intensity_level", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["earthquake_id"],
            ["earthquakes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("earthquake_id", "revision", "location_id", name="uq_impact_revision"),
    )
    op.create_index(
        op.f("ix_impact_estimates_earthquake_id"),
        "impact_estimates",
        ["earthquake_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_impact_estimates_location_id"), "impact_estimates", ["location_id"], unique=False
    )
    op.create_table(
        "notification_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("earthquake_id", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "delivered", "failed", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["earthquake_id"],
            ["earthquakes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["webhook_endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint_id", "idempotency_key", name="uq_job_idempotency"),
    )
    op.create_index(
        op.f("ix_notification_jobs_earthquake_id"),
        "notification_jobs",
        ["earthquake_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_jobs_endpoint_id"), "notification_jobs", ["endpoint_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_jobs_next_attempt_at"),
        "notification_jobs",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_jobs_status"), "notification_jobs", ["status"], unique=False
    )
    op.create_table(
        "source_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("raw_message_id", sa.String(length=36), nullable=False),
        sa.Column("earthquake_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_event_id", sa.String(length=128), nullable=False),
        sa.Column("report_number", sa.Integer(), nullable=False),
        sa.Column("report_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origin_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hypocenter", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("depth_km", sa.Float(), nullable=True),
        sa.Column("max_intensity", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum("preliminary", "reviewed", "final", "cancelled", name="eventstatus"),
            nullable=False,
        ),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["earthquake_id"],
            ["earthquakes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reports_origin_location",
        "source_reports",
        ["origin_time", "latitude", "longitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_reports_earthquake_id"), "source_reports", ["earthquake_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_reports_origin_time"), "source_reports", ["origin_time"], unique=False
    )
    op.create_index(
        op.f("ix_source_reports_raw_message_id"), "source_reports", ["raw_message_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_reports_report_time"), "source_reports", ["report_time"], unique=False
    )
    op.create_index(op.f("ix_source_reports_source"), "source_reports", ["source"], unique=False)
    op.create_index(
        op.f("ix_source_reports_source_event_id"),
        "source_reports",
        ["source_event_id"],
        unique=False,
    )
    op.create_table(
        "delivery_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_excerpt", sa.String(length=1000), nullable=True),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["notification_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_attempts_job_id"), "delivery_attempts", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_attempts_job_id"), table_name="delivery_attempts")
    op.drop_table("delivery_attempts")
    op.drop_index(op.f("ix_source_reports_source_event_id"), table_name="source_reports")
    op.drop_index(op.f("ix_source_reports_source"), table_name="source_reports")
    op.drop_index(op.f("ix_source_reports_report_time"), table_name="source_reports")
    op.drop_index(op.f("ix_source_reports_raw_message_id"), table_name="source_reports")
    op.drop_index(op.f("ix_source_reports_origin_time"), table_name="source_reports")
    op.drop_index(op.f("ix_source_reports_earthquake_id"), table_name="source_reports")
    op.drop_index("ix_reports_origin_location", table_name="source_reports")
    op.drop_table("source_reports")
    op.drop_index(op.f("ix_notification_jobs_status"), table_name="notification_jobs")
    op.drop_index(op.f("ix_notification_jobs_next_attempt_at"), table_name="notification_jobs")
    op.drop_index(op.f("ix_notification_jobs_endpoint_id"), table_name="notification_jobs")
    op.drop_index(op.f("ix_notification_jobs_earthquake_id"), table_name="notification_jobs")
    op.drop_table("notification_jobs")
    op.drop_index(op.f("ix_impact_estimates_location_id"), table_name="impact_estimates")
    op.drop_index(op.f("ix_impact_estimates_earthquake_id"), table_name="impact_estimates")
    op.drop_table("impact_estimates")
    op.drop_index(op.f("ix_event_revisions_earthquake_id"), table_name="event_revisions")
    op.drop_table("event_revisions")
    op.drop_table("webhook_endpoints")
    op.drop_table("source_health")
    op.drop_index(op.f("ix_raw_messages_source"), table_name="raw_messages")
    op.drop_index(op.f("ix_raw_messages_received_at"), table_name="raw_messages")
    op.drop_table("raw_messages")
    op.drop_table("locations")
    op.drop_index(op.f("ix_earthquakes_origin_time"), table_name="earthquakes")
    op.drop_index(op.f("ix_earthquakes_magnitude"), table_name="earthquakes")
    op.drop_index(op.f("ix_earthquakes_hypocenter"), table_name="earthquakes")
    op.drop_table("earthquakes")
    # ### end Alembic commands ###
